### PR TITLE
fix(gha): add release-please

### PR DESCRIPTION
**Pull request by ruzickap**
Fix Vagrant issue:

```console
An error occurred executing a remote WinRM command.

Shell: Cmd
Command: hostname
Message: Digest initialization failed: initialization error
Error: Process completed with exit code 1.
```

### CODE REVIEW

**Comment by abbbi** [comment]
hi,

thats an issue in vagrant fixed in the latest vagrant 2.3.8 dev build

**Comment by ruzickap** [comment]
Good to know - then I need to wait for 2.3.8 release :-)
Thank you for letting me know...

**Comment by abbbi** [comment]
heres the reference: https://github.com/hashicorp/vagrant/issues/13211#issuecomment-1601665940

**Comment by ricopicone** [comment]
> heres the reference: [hashicorp/vagrant#13211 (comment)](https://github.com/hashicorp/vagrant/issues/13211#issuecomment-1601665940)

I'm getting this error on a macOS (arm) host with the latest nightly build. The link provided doesn't have a darwin build. Is there a fixed version for my situation? Thanks!

**Comment by ruzickap** [comment]
Currently the builds are broken. 
I hope Vagrant v2.3.8 will solve this situation. Once there will be a new "stable" version I will look at it...

If there are bugs in the "nightly" feel free to report it to Vagrant - I probably can not help with it :-(

Thanks...

**Comment by braaqwesi** [comment]
Does this fix works for MaC OSx.. i am stil facing the issue

**Comment by ruzickap** [comment]
I doubt... 
Maybe new Vagrant release v2.3.8 will help...

**Pull request merged**
